"""auth and multi-family

Revision ID: 203d17bc8cba
Revises: cf2c37296631
Create Date: 2026-05-08 00:13:42.913253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '203d17bc8cba'
down_revision: Union[str, None] = 'cf2c37296631'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('families',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('family_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_family_id'), ['family_id'], unique=False)

    op.create_table('whatsapp_enrollments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('family_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('whatsapp_number', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('whatsapp_enrollments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_whatsapp_enrollments_family_id'), ['family_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_whatsapp_enrollments_whatsapp_number'), ['whatsapp_number'], unique=True)

    with op.batch_alter_table('bug_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('family_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_bug_logs_family_id'), ['family_id'], unique=False)
        batch_op.create_foreign_key('fk_bug_logs_family_id', 'families', ['family_id'], ['id'])

    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('family_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_conversations_family_id'), ['family_id'], unique=False)
        batch_op.create_foreign_key('fk_conversations_family_id', 'families', ['family_id'], ['id'])

    with op.batch_alter_table('financial_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('family_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_financial_records_family_id'), ['family_id'], unique=False)
        batch_op.create_foreign_key('fk_financial_records_family_id', 'families', ['family_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('financial_records', schema=None) as batch_op:
        batch_op.drop_constraint('fk_financial_records_family_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_financial_records_family_id'))
        batch_op.drop_column('family_id')

    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_constraint('fk_conversations_family_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_conversations_family_id'))
        batch_op.drop_column('family_id')

    with op.batch_alter_table('bug_logs', schema=None) as batch_op:
        batch_op.drop_constraint('fk_bug_logs_family_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_bug_logs_family_id'))
        batch_op.drop_column('family_id')

    with op.batch_alter_table('whatsapp_enrollments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_whatsapp_enrollments_whatsapp_number'))
        batch_op.drop_index(batch_op.f('ix_whatsapp_enrollments_family_id'))

    op.drop_table('whatsapp_enrollments')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_family_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('families')
    # ### end Alembic commands ###
