"""add loans table

Revision ID: 8f1b23bd6c7a
Revises: b9817035f285
Create Date: 2026-05-09 17:30:09.688136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f1b23bd6c7a'
down_revision: Union[str, None] = 'b9817035f285'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('family_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('lender', sa.String(length=120), nullable=False),
    sa.Column('principal', sa.Float(), nullable=False),
    sa.Column('interest_rate', sa.Float(), nullable=True),
    sa.Column('term_months', sa.Integer(), nullable=True),
    sa.Column('monthly_payment', sa.Float(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('payment_due_day', sa.Integer(), nullable=True),
    sa.Column('current_balance', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_loans_family_id'), ['family_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_loans_family_id'))

    op.drop_table('loans')
    # ### end Alembic commands ###
