"""add recurring_expenses and payment_reminders

Revision ID: 9c740d1f3e7c
Revises: 8f1b23bd6c7a
Create Date: 2026-05-09 19:09:03.968901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c740d1f3e7c'
down_revision: Union[str, None] = '8f1b23bd6c7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_reminders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('family_id', sa.Integer(), nullable=False),
    sa.Column('target_type', sa.String(length=20), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('family_id', 'target_type', 'target_id', 'due_date', 'kind', name='uq_payment_reminder_dedup')
    )
    with op.batch_alter_table('payment_reminders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_reminders_family_id'), ['family_id'], unique=False)

    op.create_table('recurring_expenses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('family_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('payment_due_day', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('account', sa.String(length=80), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recurring_expenses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recurring_expenses_family_id'), ['family_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recurring_expenses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recurring_expenses_family_id'))

    op.drop_table('recurring_expenses')
    with op.batch_alter_table('payment_reminders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_reminders_family_id'))

    op.drop_table('payment_reminders')
    # ### end Alembic commands ###
