"""add is_superadmin to users

Revision ID: a897d7902c0f
Revises: 203d17bc8cba
Create Date: 2026-05-08 00:19:40.841807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a897d7902c0f'
down_revision: Union[str, None] = '203d17bc8cba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column(
            'is_superadmin', sa.Boolean(), nullable=False,
            server_default=sa.text("0"),
        ))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_superadmin')

    # ### end Alembic commands ###
