"""add currency columns

Revision ID: ae2ce5316f37
Revises: 9c740d1f3e7c
Create Date: 2026-05-09 19:33:32.974239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae2ce5316f37'
down_revision: Union[str, None] = '9c740d1f3e7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # NOT NULL with server_default so existing rows are backfilled to MYR.
    with op.batch_alter_table('families', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default_currency', sa.String(length=10), nullable=False, server_default="MYR"))

    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('currency', sa.String(length=10), nullable=False, server_default="MYR"))

    with op.batch_alter_table('recurring_expenses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('currency', sa.String(length=10), nullable=False, server_default="MYR"))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recurring_expenses', schema=None) as batch_op:
        batch_op.drop_column('currency')

    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.drop_column('currency')

    with op.batch_alter_table('families', schema=None) as batch_op:
        batch_op.drop_column('default_currency')

    # ### end Alembic commands ###
