"""ledger: bank_accounts + account_balances + records.account

Revision ID: b9817035f285
Revises: a897d7902c0f
Create Date: 2026-05-08 20:30:46.230156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9817035f285'
down_revision: Union[str, None] = 'a897d7902c0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_balances',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('family_id', sa.Integer(), nullable=False),
    sa.Column('account_name', sa.String(length=80), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('account_balances', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_account_balances_account_name'), ['account_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_account_balances_family_id'), ['family_id'], unique=False)

    op.create_table('bank_accounts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('family_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bank_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bank_accounts_family_id'), ['family_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bank_accounts_name'), ['name'], unique=False)

    with op.batch_alter_table('financial_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account', sa.String(length=80), nullable=True))
        batch_op.create_index(batch_op.f('ix_financial_records_account'), ['account'], unique=False)

    # Backfill: existing savings rows already have the bank in `source` —
    # copy it to `account` so per-account ledger picks them up.
    op.execute(
        "UPDATE financial_records SET account = source "
        "WHERE record_type = 'savings' AND source IS NOT NULL AND source != ''"
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('financial_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_financial_records_account'))
        batch_op.drop_column('account')

    with op.batch_alter_table('bank_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bank_accounts_name'))
        batch_op.drop_index(batch_op.f('ix_bank_accounts_family_id'))

    op.drop_table('bank_accounts')
    with op.batch_alter_table('account_balances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_account_balances_family_id'))
        batch_op.drop_index(batch_op.f('ix_account_balances_account_name'))

    op.drop_table('account_balances')
    # ### end Alembic commands ###
