"""initial schema

Revision ID: cf2c37296631
Revises: 
Create Date: 2026-05-08 00:04:25.148994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf2c37296631'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bug_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('error_type', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('file_name', sa.String(length=200), nullable=True),
    sa.Column('function_name', sa.String(length=200), nullable=True),
    sa.Column('traceback_text', sa.Text(), nullable=True),
    sa.Column('auto_fixed', sa.Integer(), nullable=True),
    sa.Column('fix_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conversations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('whatsapp_number', sa.String(length=50), nullable=True),
    sa.Column('current_record_id', sa.Integer(), nullable=True),
    sa.Column('current_step', sa.String(length=50), nullable=True),
    sa.Column('current_question', sa.Text(), nullable=True),
    sa.Column('expected_answer_type', sa.String(length=50), nullable=True),
    sa.Column('options_json', sa.Text(), nullable=True),
    sa.Column('state', sa.String(length=20), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversations_whatsapp_number'), ['whatsapp_number'], unique=True)

    op.create_table('financial_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('whatsapp_number', sa.String(length=50), nullable=True),
    sa.Column('record_type', sa.String(length=20), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('merchant', sa.String(length=200), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('source_text', sa.Text(), nullable=True),
    sa.Column('source_type', sa.String(length=20), nullable=True),
    sa.Column('whatsapp_message_id', sa.String(length=120), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('missing_fields', sa.Text(), nullable=True),
    sa.Column('raw_ai_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('financial_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_financial_records_whatsapp_number'), ['whatsapp_number'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('financial_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_financial_records_whatsapp_number'))

    op.drop_table('financial_records')
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversations_whatsapp_number'))

    op.drop_table('conversations')
    op.drop_table('bug_logs')
    # ### end Alembic commands ###
